"""Baseline schema — the eight tables M2 built.

The first revision, generated from `crumblr.persistence.schema` at the point
where ordinary runs began writing data they might miss (review 1.4 F-020,
review 1.6 F-023). Until then `metadata.create_all` was defensible because the
database was disposable; it stopped being so the moment a journal, sealed
capsules, risk-session snapshots and raw market data started accumulating in it.

There is no data migration here because there was no deployed database to
migrate — this creates the schema the code already expected. Every change from
here on is a new revision, and `tests/integration/test_migrations.py` asserts
that a migrated database and the application's own metadata do not disagree.

Revision ID: ce70efeb9fe9
Revises:
Create Date: 2026-08-18
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ce70efeb9fe9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then reviewed against schema.py column by column.
    op.create_table(
        "config_versions",
        sa.Column("config_version", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("config_version"),
    )
    op.create_table(
        "decision_capsules",
        sa.Column("capsule_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("occurred_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=64), nullable=False),
        sa.Column("broker_symbol", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("strategy_version", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("feature_set_version", sa.String(length=128), nullable=False),
        sa.Column("risk_config_version", sa.String(length=128), nullable=False),
        sa.Column("code_commit", sa.String(length=128), nullable=False),
        sa.Column("provenance_fingerprint", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("capsule_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index(
        "ix_capsules_correlation", "decision_capsules", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_capsules_replay_order",
        "decision_capsules",
        ["occurred_at_utc", "sequence"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("schema_version >= 1", name="events_schema_version_positive"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index("ix_events_correlation", "events", ["correlation_id"], unique=False)
    op.create_index(
        "ix_events_replay_order", "events", ["occurred_at_utc", "sequence"], unique=False
    )
    op.create_index(
        "ix_events_type_time", "events", ["event_type", "occurred_at_utc"], unique=False
    )
    op.create_table(
        "instrument_specs",
        sa.Column("spec_version", sa.Text(), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=64), nullable=False),
        sa.Column("broker_symbol", sa.String(length=64), nullable=False),
        sa.Column("captured_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "first_seen_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("contract_size", sa.Numeric(), nullable=False),
        sa.Column("point", sa.Numeric(), nullable=False),
        sa.Column("tick_size", sa.Numeric(), nullable=False),
        sa.Column("tick_value", sa.Numeric(), nullable=False),
        sa.Column("volume_min", sa.Numeric(), nullable=False),
        sa.Column("volume_max", sa.Numeric(), nullable=False),
        sa.Column("volume_step", sa.Numeric(), nullable=False),
        sa.Column("digits", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("spec_version"),
    )
    op.create_index(
        "ix_specs_symbol", "instrument_specs", ["canonical_symbol", "captured_at_utc"], unique=False
    )
    op.create_table(
        "market_bars",
        sa.Column("bar_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=64), nullable=False),
        sa.Column("broker_symbol", sa.String(length=64), nullable=False),
        sa.Column("timeframe", sa.String(length=16), nullable=False),
        sa.Column("open_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("open", sa.Numeric(), nullable=False),
        sa.Column("high", sa.Numeric(), nullable=False),
        sa.Column("low", sa.Numeric(), nullable=False),
        sa.Column("close", sa.Numeric(), nullable=False),
        sa.Column("tick_volume", sa.BigInteger(), nullable=False),
        sa.Column("real_volume", sa.BigInteger(), nullable=True),
        sa.Column("spread_points", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=128), nullable=True),
        sa.Column("tick_count", sa.Integer(), nullable=True),
        sa.Column("data_quality", sa.String(length=16), nullable=False),
        sa.Column("anomalies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("high >= low", name="market_bars_high_at_least_low"),
        sa.PrimaryKeyConstraint("bar_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index(
        "ix_bars_replay_order",
        "market_bars",
        ["canonical_symbol", "timeframe", "open_time_utc", "sequence"],
        unique=False,
    )
    op.create_index("ix_bars_source_time", "market_bars", ["source", "open_time_utc"], unique=False)
    op.create_table(
        "market_ticks",
        sa.Column("tick_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("canonical_symbol", sa.String(length=64), nullable=False),
        sa.Column("broker_symbol", sa.String(length=64), nullable=False),
        sa.Column("event_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("bid", sa.Numeric(), nullable=False),
        sa.Column("ask", sa.Numeric(), nullable=False),
        sa.Column("last", sa.Numeric(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("flags", sa.BigInteger(), nullable=True),
        sa.Column("data_quality", sa.String(length=16), nullable=False),
        sa.Column("anomalies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("tick_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index(
        "ix_ticks_replay_order",
        "market_ticks",
        ["canonical_symbol", "event_time_utc", "sequence"],
        unique=False,
    )
    op.create_index(
        "ix_ticks_source_time", "market_ticks", ["source", "event_time_utc"], unique=False
    )
    op.create_table(
        "risk_session_states",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("trading_day", sa.Date(), nullable=False),
        sa.Column("session_start_equity", sa.Numeric(), nullable=False),
        sa.Column("current_equity", sa.Numeric(), nullable=False),
        sa.Column("peak_equity", sa.Numeric(), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(), nullable=False),
        sa.Column("max_drawdown_fraction", sa.Numeric(), nullable=False),
        sa.Column("max_session_loss_fraction", sa.Numeric(), nullable=False),
        sa.Column("open_risk_fraction", sa.Numeric(), nullable=False),
        sa.Column("open_position_count", sa.Integer(), nullable=False),
        sa.Column("occurred_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index(
        "ix_risk_session_day", "risk_session_states", ["trading_day", "sequence"], unique=False
    )
    op.create_index("ix_risk_session_order", "risk_session_states", ["sequence"], unique=False)
    op.create_table(
        "safety_state_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("occurred_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tripped_by", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_index("ix_safety_state_order", "safety_state_events", ["sequence"], unique=False)


def downgrade() -> None:
    # Drops everything. Only ever appropriate against a disposable database.
    op.drop_index("ix_safety_state_order", table_name="safety_state_events")
    op.drop_table("safety_state_events")
    op.drop_index("ix_risk_session_order", table_name="risk_session_states")
    op.drop_index("ix_risk_session_day", table_name="risk_session_states")
    op.drop_table("risk_session_states")
    op.drop_index("ix_ticks_source_time", table_name="market_ticks")
    op.drop_index("ix_ticks_replay_order", table_name="market_ticks")
    op.drop_table("market_ticks")
    op.drop_index("ix_bars_source_time", table_name="market_bars")
    op.drop_index("ix_bars_replay_order", table_name="market_bars")
    op.drop_table("market_bars")
    op.drop_index("ix_specs_symbol", table_name="instrument_specs")
    op.drop_table("instrument_specs")
    op.drop_index("ix_events_type_time", table_name="events")
    op.drop_index("ix_events_replay_order", table_name="events")
    op.drop_index("ix_events_correlation", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_capsules_replay_order", table_name="decision_capsules")
    op.drop_index("ix_capsules_correlation", table_name="decision_capsules")
    op.drop_table("decision_capsules")
    op.drop_table("config_versions")
