"""Domain contracts shared by every component.

Nothing in this package may import a broker SDK, a database driver or a
strategy. It is the vocabulary the rest of the system is written in.
"""

from crumblr.domain.enums import (
    TRADEABLE_DATA_QUALITY,
    DataQuality,
    EntryType,
    Environment,
    IncidentSeverity,
    KillSwitchState,
    OrderState,
    ReasonCode,
    Regime,
    RiskVerdict,
    SessionState,
    Side,
    SupervisorVerdict,
)
from crumblr.domain.events import (
    EVENT_PAYLOAD_TYPES,
    EvaluationCompleted,
    Event,
    EventType,
    OrderCheckCompleted,
    OrderResultReceived,
    OrderSubmitted,
    PositionChanged,
    ReconciliationCompleted,
    SignalGenerated,
    SystemHalted,
    build_event,
    decode_event,
    event_type_for,
)
from crumblr.domain.hashing import canonical_json, fingerprint
from crumblr.domain.models import (
    AccountState,
    ApprovedOrder,
    Bar,
    Contract,
    DecisionCapsule,
    ExecutionResult,
    Incident,
    InstrumentSpec,
    MarketSnapshot,
    PositionState,
    RiskDecision,
    SupervisorDecision,
    TradeIntent,
)
from crumblr.domain.money import (
    ZERO,
    ExactDecimal,
    Price,
    RiskFraction,
    Volume,
    points_to_price,
    price_to_points,
    quantize_price,
    tick_size_for_digits,
)
from crumblr.domain.timeutils import UtcDatetime, age_ms, utc_now

__all__ = [
    "EVENT_PAYLOAD_TYPES",
    "TRADEABLE_DATA_QUALITY",
    "ZERO",
    "AccountState",
    "ApprovedOrder",
    "Bar",
    "Contract",
    "DataQuality",
    "DecisionCapsule",
    "EntryType",
    "Environment",
    "EvaluationCompleted",
    "Event",
    "EventType",
    "ExactDecimal",
    "ExecutionResult",
    "Incident",
    "IncidentSeverity",
    "InstrumentSpec",
    "KillSwitchState",
    "MarketSnapshot",
    "OrderCheckCompleted",
    "OrderResultReceived",
    "OrderState",
    "OrderSubmitted",
    "PositionChanged",
    "PositionState",
    "Price",
    "ReasonCode",
    "ReconciliationCompleted",
    "Regime",
    "RiskDecision",
    "RiskFraction",
    "RiskVerdict",
    "SessionState",
    "Side",
    "SignalGenerated",
    "SupervisorDecision",
    "SupervisorVerdict",
    "SystemHalted",
    "TradeIntent",
    "UtcDatetime",
    "Volume",
    "age_ms",
    "build_event",
    "canonical_json",
    "decode_event",
    "event_type_for",
    "fingerprint",
    "points_to_price",
    "price_to_points",
    "quantize_price",
    "tick_size_for_digits",
    "utc_now",
]
